## Bash Configuration ##

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Set command line editing mode to vi
set -o vi

## History Settings
# Ignore duplicates (&), ls, bg, fg, exit and any command starting with whitespaces
export HISTCONTROL=ignoreboth
export HISTIGNORE="[ \t]*:&:ls:[bf]g:exit"

shopt -s cmdhist      # Keep multiline commands as one command in history
shopt -s histappend   # Keep multi-session history w/o losing one or the other
shopt -s checkwinsize # check the window size after each command and, if necessary, update the values of LINES and COLUMNS.

# Key bindings, up/down arrow searches through history
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'
bind '"\eOA": history-search-backward'
bind '"\eOB": history-search-forward'

## Git Stuff ##
source ~/.bash_scripts/git-completion.bash
source ~/.bash_scripts/git-alias.bash
source ~/.bash_scripts/git-prompt.sh
source ~/.bash_scripts/git-prompt.bash

# Start ssh-agent if its not already running
source ~/.bash_scripts/ssh_agent.bash

# ===== Shell agnostic settings ===== #
source ~/.profile
