" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible
"let mapleader = ","

" Load plugins that ship with Vim
runtime macros/matchit.vim
runtime ftplugin/man.vim

" ================ Pathogen Init ======================
call pathogen#infect()
call pathogen#helptags()

" ================ General ======================
set backspace=indent,eol,start
set history=500
set incsearch
set visualbell t_vb=
set hidden
set autoread
set nojoinspaces
set nrformats=
if has('mouse')
  set mouse=a
endif

set ignorecase
set smartcase

" ================ Appearance ======================
set ruler
set showcmd
set showmode
set laststatus=2
set list listchars=tab:▸\ ,trail:·
set number

" When the terminal has colors, enable syntax+search highlighting
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
endif

" ================ Indentation ======================
set autoindent
set smartindent
set smarttab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set expandtab

" Remove trailing whitespaces
autocmd FileType scala,java,groovy,python,perl,c autocmd BufWritePre <buffer> :call setline(1,map(getline(1,"$"),'substitute(v:val,"\\s\\+$","","")'))

filetype plugin on
filetype indent on

" ================ Disable swapfile and backup ================
set nobackup
set noswapfile
set nowb

" ================ Scrolling ===================
set scrolloff=5
set sidescrolloff=15
set sidescroll=1

" ================ Completion =======================
set wildmode=list:longest
set wildmenu                        "enable ctrl-n and ctrl-p to scroll thru matches
set wildignore=*.o,*.obj,*~         "stuff to ignore when tab completing
set wildignore+=*DS_Store*
set wildignore+=*/tmp/*,*.so,*.swp,*.zip
set wildignore+=*\\tmp\\*,*.exe
set wildignore+=*.png,*.jpg,*.gif
set wildignore+=*.class,*.jar

" ================ Vimdiff =======================
set diffopt+=iwhite           "ignore whitespaces in vimdiff

" ================ Persistent Undo ==================
" Keep undo history across sessions, by storing in file.

if has('persistent_undo')
    silent !mkdir -p ~/.vimundos/backups > /dev/null 2>&1
    set undodir=~/.vimundos/backups
    set undofile
endif

" ===== Color Scheme =====
set t_Co=256
set bg=light
colorscheme solarized

" Get rid of the annoying paren matching
let loaded_matchparen = 1

" ========== Customizing Plugins =========
" === Powerline ===
let g:Powerline_symbols = 'fancy'

" === CtrlP ===
let g:ctrlp_custom_ignore = {
    \ 'dir':  '\v[\/](\.git|\.hg|\.svn)$',
    \ 'file': '\.exe$\|\.so$\|\.dll$\|\.class$\|\.jar$\|\.zip$',
    \ }

" ========== Key Mappings ==========
nmap <leader>pp :set invpaste<CR>
nmap <leader>mr :CtrlPMRUFiles<CR>
nmap <silent> <leader>/ :nohlsearch<CR>

cmap qq :qall<CR>

" Change Working Directory to that of the current file
cmap cwd lcd %:p:h
cmap cd. lcd %:p:h

" Edit mode - Copied from http://vimcasts.org/e/14
cnoremap %% <C-R>=expand('%:h').'/'<CR>
map <leader>ew :e %%
map <leader>es :sp %%
map <leader>ev :vsp %%
map <leader>et :tabe %%

" Pinky saver
" nnoremap ; :

" Desired cursor movement when line wrapping is on
nnoremap j gj
nnoremap k gk

" Tslime keybindings
vmap <C-c><C-c> <Plug>SendSelectionToTmux
nmap <C-c><C-c> <Plug>NormalModeSendToTmux
nmap <C-c>r <Plug>SetTmuxVars

" Fugitive keybindings
nnoremap <silent> <leader>gs :Gstatus<CR>
nnoremap <silent> <leader>gd :Gdiff<CR>
nnoremap <silent> <leader>gc :Gcommit<CR>
nnoremap <silent> <leader>gb :Gblame<CR>
nnoremap <silent> <leader>gl :Glog<CR>

" ======== Local Customizations ========
" Use local vimrc if available
if filereadable(expand("~/.vimrc.local"))
    source ~/.vimrc.local
endif

" Use local gvimrc if available and gui is running
if has('gui_running')
    if filereadable(expand("~/.gvimrc.local"))
        source ~/.gvimrc.local
    endif
endif

