# Path to your oh-my-zsh configuration.
ZSH=$HOME/dotfiles/zsh_modules/oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="juanghurtado"
ZSH_THEME="gozilla"
ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git gradle dirpersist ssh-agent vi-mode)
# Other interesting plugins: history-substring-search, git-flow, grails

source $ZSH/oh-my-zsh.sh

# ====================================== #
# ===== Customize to your needs... ===== #
# ====================================== #

# ===== History Configuration ===== #
HISTSIZE=5000            # number of many lines to keep in memory
SAVEHIST=5000            # number of history entries to save to disk
HISTFILE=~/.zsh_history  # location of history file
HISTDUP=erase            # erase duplicates in the history file
setopt appendhistory     # append history to the history file (no overwriting)
setopt sharehistory      # share history across terminals
setopt incappendhistory  # immediately append to the history file, not just when a term is killed

# ===== z-zsh setup ===== # 
. ~/dotfiles/zsh_modules/z-zsh/z.sh
function precmd () {
      z --add "$(pwd -P)"
}

# ===== Shell agnostic settings ===== #
source ~/.profile

