export TERM=xterm-256color

# Path to your oh-my-zsh configuration.
ZSH=$HOME/dotfiles/zsh_modules/oh-my-zsh
ZSH_CUSTOM=$HOME/dotfiles/zsh_modules/omz-custom/plugins/

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="juanghurtado"
ZSH_THEME="gozilla"
ZSH_THEME="robbyrussell"
ZSH_THEME="arun/arun"
#ZSH_THEME="powerlevel9k/powerlevel9k"

POWERLEVEL9K_MODE='awesome-patched'                      #... or 'awesome-fontconfig' if using font config
#POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
#POWERLEVEL9K_SHORTEN_DELIMITER=""
#POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
POWERLEVEL9K_STATUS_VERBOSE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs history)
POWERLEVEL9K_SHOW_CHANGESET=true
POWERLEVEL9K_CHANGESET_HASH_LENGTH=6
POWERLEVEL9K_COLOR_SCHEME='light'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_HISTORY_FOREGROUND="white"
POWERLEVEL9K_HISTORY_BACKGROUND="black"


# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git gradle dirpersist ssh-agent zsh-syntax-highlighting history-substring-search)
# Other interesting plugins: git-flow, grails

source $ZSH/oh-my-zsh.sh

# ====================================== #
# ===== Customize to your needs... ===== #
# ====================================== #

source $ZSH/../../zsh_modules/omz-custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main pattern)
ZSH_HIGHLIGHT_STYLES[path]=fg=cyan,underline
ZSH_HIGHLIGHT_PATTERNS+=('rm *' 'fg=white,bold,bg=red')

set -o vi

# ===== Zsh customization scripts ===== #
export MY_JUMP_UTIL="fasd"
if [[ -f ~/.custom_zsh.sh ]] then;
    source ~/.custom_zsh.sh
fi
for config_file (~/dotfiles/zsh_scripts/*.zsh) source $config_file

# ===== Shell agnostic settings ===== #
source ~/.profile

