# Path to your oh-my-zsh configuration.
ZSH=$HOME/dotfiles/zsh_modules/oh-my-zsh
ZSH_CUSTOM=$HOME/dotfiles/zsh_modules/omz-custom

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="juanghurtado"
ZSH_THEME="gozilla"
ZSH_THEME="robbyrussell"
ZSH_THEME="arun"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git gradle dirpersist ssh-agent zsh-syntax-highlighting history-substring-search)
# Other interesting plugins: git-flow, grails

source $ZSH/oh-my-zsh.sh

# ====================================== #
# ===== Customize to your needs... ===== #
# ====================================== #

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main pattern)
ZSH_HIGHLIGHT_STYLES[path]='fg=cyan'
ZSH_HIGHLIGHT_PATTERNS+=('rm *' 'fg=white,bold,bg=red')

set -o vi

# ===== Zsh customization scripts ===== #
export MY_JUMP_UTIL="fasd"
if [[ -f ~/.custom_zsh.sh ]] then;
    source ~/.custom_zsh.sh
fi
for config_file (~/dotfiles/zsh_scripts/*.zsh) source $config_file

# ===== Shell agnostic settings ===== #
source ~/.profile

